export const metadata = {
    title: "Auto Wheels | Videos",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({ children }) {
    return <>{children}</>;
  }